[package]
name = "cost-bench"
version = "0.1.0"
authors = ["Reed Rosenbluth <331327+reedrosenbluth@users.noreply.github.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3.4"

[dependencies]
rand = "0.8.3"
lazy_static = "1.4.0"

[dependencies.stackslib]
#path = "../stacks-blockchain"
git = "https://github.com/stacks-network/stacks-core"
branch = "feat/clarity-wasm-next"
features = ["testing"]
package = "stackslib"

[dependencies.secp256k1]
version = "0.19.0"
features = ["serde", "recovery"]

[dependencies.rusqlite]
version = "0.28"
features = ["blob", "serde_json", "i128_blob", "bundled", "trace"]

[lib]
name = "benchmarking_lib"
path = "src/lib.rs"

[[bench]]
name = "bench"
harness = false

[profile.bench]
opt-level = 3
